#ifndef COMMUNITY_CHEST_CARDS_H
#define COMMUNITY_CHEST_CARDS_H

class CommunityChest{
public:
	enum Card{
		ADVANCE_TO_GO,
		BANK_ERROR_IN_YOUR_FAVOR,
		DOCTORS_FEE,
		FROM_SALE_OF_STOCK_YOU_GET_50,
		GET_OUT_OF_JAIL_FREE,
		GO_TO_JAIL,
		GRAND_OPERA_NIGHT,
		HOLIDAY_FUND_MATURES,
		INCOME_TAX_REFUND,
		IT_IS_YOUR_BIRTHDAY,
		LIFE_INSURANCE_MATURES,
		PAY_HOSPITAL_FEES,
		PAY_SCHOOL_FEES,
		RECEIVE_25_CONSULTANCY_FEE,
		YOU_ARE_ASSESSED_FOR_STREET_REPAIR,
		YOU_HAVE_WON_SECOND_PRIZE_IN_A_BEAUTY_CONTEST,
		YOU_INHERIT_100,

		NUM_CARDS,
	};
	static const char* GetCardName(Card card);
private:
	static const char* card_name[NUM_CARDS];
};

#endif